### ISSUE TITLE
Incorrect @angular/compiler resolution in angular-ngc example

### ISSUE THREAD

**Issue by arobinson** [aspect-build/bazel-examples#111]
Angular tests run with JIT, not AOT for tests. While writing my own Bazel build for my Angular application, I was using the `angular-ngc` as an example to setup Karma tests. While the rudimentary tests are passing, the test environment is not correct and the compiler is failing during the execution of the tests.

To be able to reproduce the issue, I have a fork of the repo:
https://github.com/arobinson/bazel-examples-bugs/tree/ngIf_resolution_issue

1. Just clone that repo (branch is `ngIf_resolution_issue`)
2. Run `bazel test //packages/lib-a:test`

Despite `CommonModule` being imported in the `TestBed.configureTestingModule`, it does not resolve the `*ngIf` in the component template. 

The `test.log` shows the issue:
```
[32m14 10 2022 15:35:28.298:INFO [Chrome Headless 106.0.5249.119 (Mac OS 10.15.7)]: [39mConnected on socket RNcGCFV8Uv9h_eg3AAAB with id 45874384
Chrome Headless 106.0.5249.119 (Mac OS 10.15.7): Executed 0 of 2 SUCCESS (0 secs / 0 secs)
[1A[2KERROR: 'NG0303: Can't bind to 'ngIf' since it isn't a known property of 'span' (used in the 'LibBComponent' component template).
If the 'ngIf' is an Angular control flow directive, please make sure that either the 'NgIf' directive or the 'CommonModule' is a part of an @NgModule where this component is declared.'
Chrome Headless 106.0.5249.119 (Mac OS 10.15.7): Executed 0 of 2 SUCCESS (0 secs / 0 secs)
ERROR: 'NG0303: Can't bind to 'ngIf' since it isn't a known property of 'span' (used in the 'LibBComponent' component template).
If the 'ngIf' is an Angular control flow directive, please make sure that either the 'NgIf' directive or the 'CommonModule' is a part of an @NgModule where this component is declared.'
[1A[2KChrome Headless 106.0.5249.119 (Mac OS 10.15.7): Executed 1 of 2 SUCCESS (0 secs / 0.01 secs)
[1A[2KChrome Headless 106.0.5249.119 (Mac OS 10.15.7) LibBComponent should create FAILED
	Should have rendered 1 span: Expected 0 to equal 1.
	    at <Jasmine>
	    at UserContext.<anonymous> (_test_bundle/src/lib/lib-b.component.spec.js:94:73)
	    at _ZoneDelegate.invoke (test_bootstrap.js:290:160)
	    at ProxyZoneSpec.onInvoke (test_bootstrap.js:2467:35)
	    at _ZoneDelegate.invoke (test_bootstrap.js:290:48)
Chrome Headless 106.0.5249.119 (Mac OS 10.15.7): Executed 2 of 2 (1 FAILED) (0 secs / 0.015 secs)
Chrome Headless 106.0.5249.119 (Mac OS 10.15.7) LibBComponent should create FAILED
	Should have rendered 1 span: Expected 0 to equal 1.
	    at <Jasmine>
	    at UserContext.<anonymous> (_test_bundle/src/lib/lib-b.component.spec.js:94:73)
	    at _ZoneDelegate.invoke (test_bootstrap.js:290:160)
	    at ProxyZoneSpec.onInvoke (test_bootstrap.js:2467:35)
	    at _ZoneDelegate.invoke (test_bootstrap.js:290:48)
[1A[2KChrome Headless 106.0.5249.119 (Mac OS 10.15.7): Executed 2 of 2 (1 FAILED) (0.001 secs / 0.015 secs)
TOTAL: 1 FAILED, 1 SUCCESS
TOTAL: 1 FAILED, 1 SUCCESS
```

FYI, if I don't use the Angular linker in the esbuild configuration, the `ngIf` issue is fixed, but all 3rd party components will blow up in the browser with an error that the JIT compiler is not available.

This is the error if the linker is not run and non-ivy components are loaded within the test:
```
Error during loading: Uncaught Error: The injectable 'PlatformLocation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available. The injectable is part of a library that has been partially compiled. However, the Angular Linker has not processed the library such that JIT compilation is used as fallback. Ideally, the library is processed using the Angular Linker to become fully AOT compiled. Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server', or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping. in http://localhost:9876/base/scripts/chunk-6GLSZBQD.js line 9815
```

Trying to run `ngcc` from the esbuild configuration instead of using the linker does not work due to Bazel restrictions on modifying the files in the sandbox:
```
Error: EPERM: operation not permitted, open '/Users/andrew/.cache/bazel/9c9edec3c6a7af13c9b81813edf110db/execroot/nw-client/bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/@angular+compiler-cli@13.1.1_gehfjlhzwtarjkj6fayghlncvu/node_modules/.ngcc_lock_file'
    at Object.openSync (node:fs:585:3)
    at writeFileSync (node:fs:2170:35)
    at NodeJSFileSystem.writeFile (file:///Users/andrew/.cache/bazel/9c9edec3c6a7af13c9b81813edf110db/execroot/nw-client/bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/@angular+compiler-cli@13.1.1_gehfjlhzwtarjkj6fayghlncvu/node_modules/@angular/compiler-cli/bundles/chunk-TI3THPMZ.js:378:5)
    at LockFileWithChildProcess.write (file:///Users/andrew/.cache/bazel/9c9edec3c6a7af13c9b81813edf110db/execroot/nw-client/bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/@angular+compiler-cli@13.1.1_gehfjlhzwtarjkj6fayghlncvu/node_modules/@angular/compiler-cli/bundles/chunk-DJRTTRF3.js:1721:13)
    at AsyncLocker.create (file:///Users/andrew/.cache/bazel/9c9edec3c6a7af13c9b81813edf110db/execroot/nw-client/bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/@angular+compiler-cli@13.1.1_gehfjlhzwtarjkj6fayghlncvu/node_modules/@angular/compiler-cli/bundles/chunk-DJRTTRF3.js:1673:30)
    at AsyncLocker.lock (file:///Users/andrew/.cache/bazel/9c9edec3c6a7af13c9b81813edf110db/execroot/nw-client/bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/@angular+compiler-cli@13.1.1_gehfjlhzwtarjkj6fayghlncvu/node_modules/@angular/compiler-cli/bundles/chunk-DJRTTRF3.js:1662:16)
    at ClusterExecutor.execute (file:///Users/andrew/.cache/bazel/9c9edec3c6a7af13c9b81813edf110db/execroot/nw-client/bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/@angular+compiler-cli@13.1.1_gehfjlhzwtarjkj6fayghlncvu/node_modules/@angular/compiler-cli/bundles/chunk-DJRTTRF3.js:1557:26)
    at mainNgcc (file:///Users/andrew/.cache/bazel/9c9edec3c6a7af13c9b81813edf110db/execroot/nw-client/bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/@angular+compiler-cli@13.1.1_gehfjlhzwtarjkj6fayghlncvu/node_modules/@angular/compiler-cli/bundles/chunk-DJRTTRF3.js:2105:19)
    at file:///Users/andrew/.cache/bazel/9c9edec3c6a7af13c9b81813edf110db/execroot/nw-client/bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/@angular+compiler-cli@13.1.1_gehfjlhzwtarjkj6fayghlncvu/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:31:11
    at file:///Users/andrew/.cache/bazel/9c9edec3c6a7af13c9b81813edf110db/execroot/nw-client/bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/@angular+compiler-cli@13.1.1_gehfjlhzwtarjkj6fayghlncvu/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:41:3
```

**Comment by arobinson** [comment]
FYI, if I don't use the Angular linker in the esbuild configuration, the `ngIf` issue is fixed, but all 3rd party components will blow up in the browser with an error that the JIT compiler is not available.

**Comment by arobinson** [comment]
Possibly related to this issue if tests need `ngcc` to run correctly:
https://github.com/aspect-build/rules_js/issues/84

**Comment by arobinson** [comment]
Here is a branch to try AOT instead of JIT for unit tests: `ngIf_resolution_issue_aot`
https://github.com/arobinson/bazel-examples-bugs/tree/ngIf_resolution_issue_aot

There are many errors with trying to use AOT instead of JIT with regards to the providers.

[test.log](https://github.com/aspect-build/bazel-examples/files/9790237/test.log)

**Comment by matthewjh** [comment]
For your issue after subtracting the Angular linker in esbuild (not the others):

> FYI, if I don't use the Angular linker in the esbuild configuration, the ngIf issue is fixed, but all 3rd party components will blow up in the browser with an error that the JIT compiler is not available.
> 
> This is the error if the linker is not run and non-ivy components are loaded within the test:
> 
> Error during loading: Uncaught Error: The injectable 'PlatformLocation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available. The injectable is part of a library that has been partially compiled. However, the Angular Linker has not processed the library such that JIT compilation is used as fallback. Ideally, the library is processed using the Angular Linker to become fully AOT compiled. Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server', or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping. in http://localhost:9876/base/scripts/chunk-6GLSZBQD.js line 9815

I think this problem is just because the compiler is not correctly included. Did you try manually importing  `import "@angular/compiler";`? You need to make sure this import comes before everything else that is loaded. The most robust way to do this is to have a separate esbuild entry point that contains just the `@angular/compiler` import (just having it at the top of a file with other imports is not enough), and add that script tag at the top of your karma HTML. We use Angular JIT with rules_js this way.

**Comment by arobinson** [comment]
Yes that was the first thing I tried. Google searches also lead to ngcc not having been run for this error
