### ISSUE TITLE
[FR]: Add an example that skips `node-gyp` installs

### ISSUE THREAD

**Issue by Aghassi** [aspect-build/bazel-examples#178]
### What is the current behavior?

Post install hooks can fail with pnpm. One that I ran into was 

```
❯ bazel test //bazel/release/internal/pusher:test
INFO: Invocation ID: f430ce78-99c5-461c-84f5-b135bd3fc6e5
INFO: Analyzed target //bazel/release/internal/pusher:test (2296 packages loaded, 35938 targets configured).
INFO: Found 1 test target...
ERROR: /Users/davidaghassi/robinhood/rh_other_alt/bazel/release/internal/pusher/BUILD.bazel:9:22: Running lifecycle hooks on npm package cpu-features@0.0.4 failed: (Exit 1): lifecycle-hooks.sh failed: error executing command (from target //bazel/release/internal/pusher:.aspect_rules_js/node_modules/cpu-features@0.0.4/lc) bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/aspect_rules_js/npm/private/lifecycle/lifecycle-hooks.sh cpu-features ../../../external/pusher_pnpm_deps__cpu-features__0.0.4/package ... (remaining 1 argument skipped)
/private/var/tmp/_bazel_davidaghassi/299af5c32fa95b8ba15b1237ac8646db/execroot/rh/bazel-out/darwin_arm64-fastbuild/bin/external/aspect_rules_js/npm/private/lifecycle/min/node-gyp-bin/node-gyp: line 5: 1211: command not found

> cpu-features@0.0.4 install /private/var/tmp/_bazel_davidaghassi/299af5c32fa95b8ba15b1237ac8646db/execroot/rh/bazel-out/darwin_arm64-fastbuild/bin/bazel/release/internal/pusher/node_modules/.aspect_rules_js/cpu-features@0.0.4/node_modules/cpu-features
> node buildcheck.js > buildcheck.gypi && node-gyp rebuild

===============================================================
Failure while running lifecycle hook for package 'cpu-features@0.0.4':

  Script:  'install'
  Command: `node buildcheck.js > buildcheck.gypi && node-gyp rebuild`

Stack trace:

spawn ENOENT
    at ChildProcess.<anonymous> (/private/var/tmp/_bazel_davidaghassi/299af5c32fa95b8ba15b1237ac8646db/execroot/rh/bazel-out/darwin_arm64-fastbuild/bin/external/aspect_rules_js/npm/private/lifecycle/min/index.min.js:1:91930)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
===============================================================
```

having docs/example/suggestion on how to solve this would make error handling better.

### Describe the feature

Adding this fix https://github.com/pnpm/pnpm/issues/4347#issuecomment-1044043721 to my `package.json` resolved my issue and let me continue building/testing.

The reason this is hard to troubleshoot is because outside of bazel, running `pnpm i` works fine.

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by twheys** [comment]
I get a similar issue when trying to build the angular app
```
➜  bazel build //:app 
INFO: Analyzed target //:app (889 packages loaded, 7588 targets configured).
INFO: Found 1 target...
ERROR: /Users/theys/github/aspect-build/bazel-examples/angular/BUILD.bazel:7:22: Running lifecycle hooks on npm package nice-napi@1.0.2 failed: (Exit 1): lifecycle-hooks.sh failed: error executing command (from target //:.aspect_rules_js/node_modules/nice-napi@1.0.2/lc) bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/aspect_rules_js/npm/private/lifecycle/lifecycle-hooks.sh nice-napi ../../../external/npm__nice-napi__1.0.2/package ... (remaining 1 argument skipped)
/private/var/tmp/_bazel_theys/676332011c2f3e295756330f3b91b35c/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/external/aspect_rules_js/npm/private/lifecycle/min/node-gyp-bin/node-gyp: line 5: 1211: command not found

> nice-napi@1.0.2 install /private/var/tmp/_bazel_theys/676332011c2f3e295756330f3b91b35c/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/nice-napi@1.0.2/node_modules/nice-napi
> node-gyp-build

===============================================================
Failure while running lifecycle hook for package 'nice-napi@1.0.2':

  Script:  'install'
  Command: `node-gyp-build`

Stack trace:

spawn ENOENT
    at ChildProcess.<anonymous> (/private/var/tmp/_bazel_theys/676332011c2f3e295756330f3b91b35c/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/external/aspect_rules_js/npm/private/lifecycle/min/index.min.js:1:91930)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
===============================================================
Target //:app failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 37.890s, Critical Path: 4.58s
INFO: 2783 processes: 1848 internal, 3 darwin-sandbox, 932 local.
```

**Comment by mtsgrd** [comment]
I also get a similar issue, but can't seem to get @Aghassi workaround to work.

```
bazel build //:app
INFO: Analyzed target //:app (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/mattias/c/bazel-examples/angular/BUILD.bazel:7:22: Running lifecycle hooks on npm package nice-napi@1.0.2 failed: (Exit 1): lifecycle-hooks.sh failed: error executing command (from target //:.aspect_rules_js/node_modules/nice-napi@1.0.2/lc) bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/aspect_rules_js/npm/private/lifecycle/lifecycle-hooks.sh nice-napi ../../../external/npm__nice-napi__1.0.2/package ... (remaining 1 argument skipped)
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '/private/var/tmp/_bazel_mattias/3027eccc8676ed26bace85ab5cf2a721/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/external/aspect_rules_js/npm/private/lifecycle/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

> nice-napi@1.0.2 install /private/var/tmp/_bazel_mattias/3027eccc8676ed26bace85ab5cf2a721/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/nice-napi@1.0.2/node_modules/nice-napi
> node-gyp-build

===============================================================
Failure while running lifecycle hook for package 'nice-napi@1.0.2':

  Script:  'install'
  Command: `node-gyp-build`

Stack trace:

Exit status 1
    at EventEmitter.<anonymous> (/private/var/tmp/_bazel_mattias/3027eccc8676ed26bace85ab5cf2a721/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/external/aspect_rules_js/npm/private/lifecycle/min/index.min.js:47:92054)
    at EventEmitter.emit (node:events:513:28)
    at ChildProcess.<anonymous> (/private/var/tmp/_bazel_mattias/3027eccc8676ed26bace85ab5cf2a721/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/external/aspect_rules_js/npm/private/lifecycle/min/index.min.js:1:195024)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
===============================================================
Target //:app failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.496s, Critical Path: 0.34s
INFO: 3 processes: 2 internal, 1 local.
FAILED: Build did NOT complete successfully
Error: bazel exited with exit code: 1
```

**Comment by catflyflyfly** [comment]
@mtsgrd This happens to people with M1 mac. Problem is while bazel is doing `npm_link_all_packages(name = "node_modules")` from `/bazel-examples/angular/BUILD.bazel:7:22`, [/npm/private/lifecycle](https://github.com/aspect-build/rules_js/tree/main/npm/private/lifecycle) couldn't do `npm install` for some reason.

Workaround:

1. go to the private dir for `/npm/private/lifecycle`. Find that dir in your log.

```
pushd
/private/var/tmp/_bazel_mattias/3027eccc8676ed26bace85ab5cf2a721/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/external/aspect_rules_js/npm/private/lifecycle
```

2. `npm install`
3. `popd` back to where you were before, then try `bazel build` again.
