### ISSUE TITLE
[Bug]: vue example doesn't work

### ISSUE THREAD

**Issue by jmmv** [aspect-build/bazel-examples#182]
### What happened?

I get the following error when trying to run the `vue` example from the `bazel-examples` directory after a fresh clone:

```
dev:/tmp/bazel-examples/vue> npm run dev

> vue-project@0.0.0 dev
> ibazel run :vite

iBazel [6:42PM]: Querying for files to watch...
Loading: 0 packages loaded
Loading: 153 packages loaded

Loading: 0 packages loaded
Loading: 0 packages loaded

iBazel [6:42PM]: Running :vite
Loading:
Loading: 0 packages loaded
Analyzing: target //:vite (0 packages loaded, 0 targets configured)
INFO: Analyzed target //:vite (36 packages loaded, 3658 targets configured).
 checking cached actions
INFO: Found 1 target...

INFO: Elapsed time: 1.312s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
Loading:
Loading: 0 packages loaded
Analyzing: target //:vite (0 packages loaded, 0 targets configured)
INFO: Analyzed target //:vite (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 2] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[709 / 739] [Prepa] Running lifecycle hooks on npm package fsevents@2.3.2 ... (23 actions, 5 running)
INFO: From Rollup libraries/simple/cjs_bundle.js:

libraries/simple/src/index.js → libraries/simple/cjs_bundle.js...
(!) Entry module "libraries/simple/src/index.js" is implicitly using "default" export mode, which means for CommonJS output that its default export is assigned to "module.exports". For many tools, such CommonJS output will not be interchangeable with the original ES module. If this is intended, explicitly set "output.exports" to either "auto" or "default", otherwise you might want to consider changing the signature of "libraries/simple/src/index.js" to use named exports only.
https://rollupjs.org/guide/en/#outputexports
libraries/simple/src/index.js
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
vue (imported by libraries/simple/src/InputText.vue?vue&type=template&id=2c159833&lang.js, libraries/simple/src/InputTextarea.vue?vue&type=template&id=3d2c14c0&lang.js)
created libraries/simple/cjs_bundle.js in 155ms
[733 / 739] Rollup libraries/simple/esm_bundle.js; 0s linux-sandbox ... (3 actions, 2 running)
INFO: From Rollup libraries/simple/esm_bundle.js:

libraries/simple/src/index.js → libraries/simple/esm_bundle.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
vue (imported by libraries/simple/src/InputText.vue?vue&type=template&id=2c159833&lang.js, libraries/simple/src/InputTextarea.vue?vue&type=template&id=3d2c14c0&lang.js)
created libraries/simple/esm_bundle.js in 158ms
Target //:vite up-to-date:
  bazel-bin/vite.sh
INFO: Elapsed time: 2.660s, Critical Path: 1.89s
INFO: 466 processes: 280 internal, 2 linux-sandbox, 184 local.
INFO: Build completed successfully, 466 total actions
INFO: Build completed successfully, 466 total actions
iBazel [6:42PM]: Starting...

################################################################################
# Did you know iBazel can invoke programs like Gazelle, buildozer, and         #
# other BUILD file generators for you automatically based on bazel output?     #
# Documentation at: https://github.com/bazelbuild/bazel-watcher#output-runner  #
################################################################################

/home/jmmv/.cache/bazel/_bazel_jmmv/5086ec9d95f5cba6669306fcf5db83b9/external/aspect_rules_js/js/private/node-patches/fs.js:797
                throw err;
                ^

Error: ENOENT: no such file or directory, readlink '/home/jmmv/.cache/bazel/_bazel_jmmv/5086ec9d95f5cba6669306fcf5db83b9/execroot/__main__/.aspect/bazelrc/common.bazelrc'
    at enoent (/home/jmmv/.cache/bazel/_bazel_jmmv/5086ec9d95f5cba6669306fcf5db83b9/external/aspect_rules_js/js/private/node-patches/fs.js:816:15)
    at /home/jmmv/.cache/bazel/_bazel_jmmv/5086ec9d95f5cba6669306fcf5db83b9/external/aspect_rules_js/js/private/node-patches/fs.js:221:39
    at /home/jmmv/.cache/bazel/_bazel_jmmv/5086ec9d95f5cba6669306fcf5db83b9/external/aspect_rules_js/js/private/node-patches/fs.js:477:32
    at FSReqCallback.oncomplete (node:fs:192:23) {
  errno: -2,
  syscall: 'readlink',
  code: 'ENOENT',
  path: '/home/jmmv/.cache/bazel/_bazel_jmmv/5086ec9d95f5cba6669306fcf5db83b9/execroot/__main__/.aspect/bazelrc/common.bazelrc'
}
```

### Version

This is running exactly as configured by `bazel-examples/vue` in revision  5c785b85cbe6efaeb0014023c75ccd625340e351 (so you can get the Bazel version from there, which apparently uses some custom binaries?).

This is on a Debian testing machine:

dev:/tmp/bazel-examples/vue> uname -a
Linux dev 6.1.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.4-1 (2023-01-07) x86_64 GNU/Linux

dev:/tmp/bazel-examples/vue> cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

dev:/tmp/bazel-examples/vue> npm --version
9.2.0

### How to reproduce

```shell
Clone the `bazel-examples` repository, run the `npm run dev` command inside `vue` as the instructions say, and get a failure.
```

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
Bazel slack thread https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1675536308753049

This looks like something to do with the bazelrc's in the examples being symlinks in the bazel-examples repository.

```
lrwxr-xr-x  1 greg  staff   43 26 Nov 19:58 ci.bazelrc -> ../../../bazelrc/.aspect/bazelrc/ci.bazelrc
lrwxr-xr-x  1 greg  staff   47 26 Nov 19:58 common.bazelrc -> ../../../bazelrc/.aspect/bazelrc/common.bazelrc
lrwxr-xr-x  1 greg  staff   48 26 Nov 19:58 common6.bazelrc -> ../../../bazelrc/.aspect/bazelrc/common6.bazelrc
lrwxr-xr-x  1 greg  staff   51 26 Nov 19:58 javascript.bazelrc -> ../../../bazelrc/.aspect/bazelrc/javascript.bazelrc
```

This is intentional so that the files in `bazelrc` are the SoT for all the examples.

Did you do a partial clone of the bazel-examples repo perhaps?

**Comment by jmmv** [comment]
@gregmagolan Nope... I did a full clone. I just tried again with exactly these commands:

```
$ cd /tmp
$ git clone https://github.com/aspect-build/bazel-examples
$ cd bazel-examples/vue
$ npx pnpm i
$ npm run dev
```

and was greeted with the error above. The symlink exists and is valid though:

```
$ readlink /home/jmmv/.cache/bazel/_bazel_jmmv/5086ec9d95f5cba6669306fcf5db83b9/execroot/__main__/.aspect/bazelrc/ci.bazelrc
../../../bazelrc/.aspect/bazelrc/ci.bazelrc
$ readlink -f /home/jmmv/.cache/bazel/_bazel_jmmv/5086ec9d95f5cba6669306fcf5db83b9/execroot/__main__/.aspect/bazelrc/ci.bazelrc
/tmp/bazel-examples/bazelrc/.aspect/bazelrc/ci.bazelrc
$ md5sum /home/jmmv/.cache/bazel/_bazel_jmmv/5086ec9d95f5cba6669306fcf5db83b9/execroot/__main__/.aspect/bazelrc/ci.bazelrc
ebe53356c45364b64b67aea7e9009ceb  /home/jmmv/.cache/bazel/_bazel_jmmv/5086ec9d95f5cba6669306fcf5db83b9/execroot/__main__/.aspect/bazelrc/ci.bazelrc
```

**Comment by gregmagolan** [comment]
I took another quick look and looks like this is indeed a problem with this target but only when it is `bazel run` which is why it wasn't caught on CI.

A `bazel build :vite` works fine... so it is something the vite is doing at runtime causing the readlink to blow up from within the node fs patches. Now that I can repro I'll figure out a fix.

**Comment by gregmagolan** [comment]
Instead of trying to reverse engineering why vite is readlinking those files, I'll just unwind the symlinks and use a script to copy over the recommended bazelrc settings to each of the examples.
